############## Rviz ##############
quit_simulation_topic: "quit_simulation"
############## Sensors ##############
ground_truth_topic: "ground_truth"
infrastructure_gps_topic: "gps/fix"
infrastructure_cams_topic: "rsu/data"
############## Map ##############
hd_map: "Town10HD_Opt"
target_fps: 60.0 # This is for the client in synch mode.
# Tf transformation tree frames
map_frame: "map"

# /**: will set the parameter string_param on all nodes,
# /**/some_node: will set the parameter string_param on nodes named some_node in any namespace,
# /foo/*: will set the parameter string_param on any node in the namespace /foo.
